// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa86QY5dfJLKIZ6DET1ZzQArBFAfCM8xw',
    appId: '1:203753188604:web:d12713c47315c2fc7abb79',
    messagingSenderId: '203753188604',
    projectId: 'flutterauthen-f288f',
    authDomain: 'flutterauthen-f288f.firebaseapp.com',
    storageBucket: 'flutterauthen-f288f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrwcn8TAXWyTz7C_T3hOhhuXLvgyqMQc',
    appId: '1:203753188604:android:94e942ae5e7338e67abb79',
    messagingSenderId: '203753188604',
    projectId: 'flutterauthen-f288f',
    storageBucket: 'flutterauthen-f288f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4X7kIuBlvR32TIkkvzNMrvYtZ6pC9oDg',
    appId: '1:203753188604:ios:64e70739fb743ce67abb79',
    messagingSenderId: '203753188604',
    projectId: 'flutterauthen-f288f',
    storageBucket: 'flutterauthen-f288f.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4X7kIuBlvR32TIkkvzNMrvYtZ6pC9oDg',
    appId: '1:203753188604:ios:5f8f98ddda3a0d777abb79',
    messagingSenderId: '203753188604',
    projectId: 'flutterauthen-f288f',
    storageBucket: 'flutterauthen-f288f.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
